### ISSUE TITLE
Autodownload

### ISSUE THREAD

**Issue by MicrocontrollersDev** [LunaNotdev/Introduction-to-modding-mc#4]
A lot of links could be made to automatically download the mods instead of taking the user to a website to download. I think this would be particularly beneficial for mods where there are multiple download options, such as Forge latest/recommended, ChatTriggers stable/legacy, etc.

If you like this idea I can PR it.

**Comment by LunaNotdev** [comment]
no

**Comment by LunaNotdev** [comment]
I intentionally did that so I don't have to keep updating mods and so people can be confident that those downloads aren't bullshit and some malware I know this sounds dumb but monkey say no

**Comment by MicrocontrollersDev** [comment]
understandable, and yeah thats why i didnt do it in one of my prs and wanted to ask first
